### PR TITLE
Changes for type_traits Version2

### PR DESCRIPTION
**Pull request by eldiener**

### CODE REVIEW

**Comment by jzmaddock** [comment]
I have a question about this change - is it not overkill to use mpl::and etc?  These were workarounds for broken compilers that couldn't handle use of && || ! etc in constant expressions (just like the old ice_or/ice_and were).  Is it not simpler and more readable to compose the expression directly using boolean operators?

**Comment by eldiener** [comment]
You mean that &&, !!, and ! actually work with compile-time constant boolean expressions <g> ?

You are right. I took the safest way I knew, which was to replace all of the ice functionality with their equivalent MPL functionality. I have been so brainwashed by how well MPL  works, once I understood it, that I honestly never even thought of using the logical operators directly.

If you think it correct not to worry about the broken compilers anymore I can rework my changes. I made the same type of changes for the other libraries where I found the deprecated type_traits ice headers were being used.

**Comment by eldiener** [comment]
"You mean that &&, !!, and ! actually work with compile-time constant boolean expressions ?" This should be a smiley.

**Comment by jzmaddock** [comment]
> You are right. I took the safest way I knew, which was to replace all 
> of the ice functionality with their equivalent MPL functionality. I 
> have been so brainwashed by how well MPL works, once I understood it, 
> that I honestly never even thought of using the logical operators 
> directly.
>
> If you think it correct not to worry about the broken compilers 
> anymore I can rework my changes. I made the same type of changes for 
> the other libraries where I found the deprecated type_traits ice 
> headers were being used.
>
 From memory, the workarounds were only really introduced for VC6: which 
is definitely not supported any more.  Personally, I find code that uses 
the operators directly is cleaner and easier to understand - it should 
also result in many fewer template instantiations which is a good thing.

Either way, many thanks for submitting PR's for these issues - I've been 
sort of holding off on these changes until the revised type_traits 
actually makes it into develop.

**Comment by eldiener** [comment]
I have changed this to use operators directly rather than mpl.

**Comment by jzmaddock** [comment]
> I have changed this to use operators directly rather than mpl.
>
OK, thanks!

**Pull request merged**
